syntax on
filetype plugin indent on
execute pathogen#infect()

let g:xml_syntax_folding=1
au FileType xml setlocal foldmethod=syntax

runtime macros/matchit.vim

nnoremap <C-i>[ vatv
nnoremap <C-i>[[ vatov

""""""""""""""""""""""
" case (in)sensitivity
""""""""""""""""""""""
set ic 
set smartcase
""""""""""""""""""""""
" tabs
""""""""""""""""""""""
set expandtab
set tabstop=4

""""""""""""""""""""""
" tabs
""""""""""""""""""""""
"set cc=80
